/*
	DESERTER = 7, //逃兵			- 濒死时曝光身份，同时有30s不受他人伤害也不能攻击他人，此时可以逃跑。时间过后，伤害降低为20%。再等90s伤害恢复到80%。

	INFECTOR = 102, //传染源 		- 满足一定条件时转化一个玩家为内鬼
	*/

ROLE <- {
	NONE = -1,
	IAF = 0, //普通IAF队员	- 普通人
	SCANNER = 1, //扫描专家 		- 预言
	BIOCHEMIST = 2, //生化专家		- 瞬间回血、秒杀，不能给自己
	IAF_LEADER = 3, //指挥官		- 额外的半条命
	SHIELD = 4, //护盾			- 制造能承受一定伤害的护盾，不能给自己
	SNIPER = 5, //狙击手		- 死亡时杀死杀死自己的玩家
	DEMO = 6, //爆破突击手	- 死亡时自爆
	DESERTER = 7, //逃兵			- 濒死时曝光身份，同时有30s不受他人伤害也不能攻击他人，此时可以逃跑。时间过后，伤害降低为20%。再等90s伤害恢复到80%。

	MAX_IAF_TEAM = 99,

	TRAITOR = 100, //内鬼			- 杀人
	TRAITOR_LEADER = 101, //内鬼首领 		- 额外的半条命
	INFECTOR = 102, //传染源 		- 满足一定条件时转化一个玩家为内鬼
	BOOMER = 103, //自爆怪 		- 死亡时自爆
	SILENCER = 104, //沉默			- 让一人失去技能
	MIMIC = 105, //模仿者		-扫描时显示为IAF

	INFECTED_OFFSET = 150,
	INFECTED_IAF = 150, //普通IAF队员	- 普通人
	INFECTED_SCANNER = 151, //扫描专家 		- 预言
	INFECTED_BIOCHEMIST = 152, //生化专家		- 瞬间回血、秒杀，不能给自己
	INFECTED_IAF_LEADER = 153, //指挥官		- 额外的半条命
	INFECTED_SHIELD = 154, //护盾			- 制造能承受一定伤害的护盾，不能给自己
	INFECTED_SNIPER = 155, //狙击手		- 死亡时杀死杀死自己的玩家
	INFECTED_DEMO = 156, //爆破突击手	- 死亡时自爆
	INFECTED_DESERTER = 157, //逃兵			- 濒死时曝光身份，同时有30s不受他人伤害也不能攻击他人，此时可以逃跑。时间过后，伤害降低为20%。再等90s

	MAX_TRAITOR_TEAM = 199,

	SPECTATOR = 255, //观战玩家
};

MENU_IDX_INT_START <- 4;
MENU_IDX_FLOAT_START <- 2;

MENU_IDX_INT <- {
	BIOCHEMIST_IS_HEAL_USED = MENU_IDX_INT_START,
	BIOCHEMIST_IS_KILL_USED = MENU_IDX_INT_START + 1,
	BIOCHEMIST_IS_HEALED = MENU_IDX_INT_START + 2,
	BIOCHEMIST_IS_KILLED = MENU_IDX_INT_START + 3,
	INFECTOR_IS_SKILL_ACTIVE = MENU_IDX_INT_START + 4,
	INFECTOR_IS_SKILL_USED = MENU_IDX_INT_START + 5,
	INFECTOR_IS_ABETED = MENU_IDX_INT_START + 6,
	SCANNER_IS_REVEALED = MENU_IDX_INT_START + 7,
	SHIELD_IS_SKILL_USED = MENU_IDX_INT_START + 8,
	SHIELD_IS_SELECTED = MENU_IDX_INT_START + 9,
	SILENCER_IS_SKILL_USED = MENU_IDX_INT_START + 10,
	SILENCER_IS_SILENCED = MENU_IDX_INT_START + 11,
	SCANNER_IS_WITHIN_RANGE = MENU_IDX_INT_START + 12,

	BIOCHEMIST_NEXT_AVAILABLE_TIME = MENU_IDX_FLOAT_START,
	INFECTOR_NEXT_AVAILABLE_TIME = MENU_IDX_FLOAT_START + 1,
	SCANNER_NEXT_AVAILABLE_TIME = MENU_IDX_FLOAT_START + 2,
	SHIELD_NEXT_AVAILABLE_TIME = MENU_IDX_FLOAT_START + 3,
	SILENCER_NEXT_AVAILABLE_TIME = MENU_IDX_FLOAT_START + 4,

};

BOOMER_SOUND <- {
	ALERT = "Traitors.Boomer_Alert",
	COUNT_DOWN = [
		"Traitors.Boomer_CountDown_0",
		"Traitors.Boomer_CountDown_1",
		"Traitors.Boomer_CountDown_2",
		"Traitors.Boomer_CountDown_3",
		"Traitors.Boomer_CountDown_4",
		"Traitors.Boomer_CountDown_5",
	],
}

MISSION_END_SOUND <- {
	IAF = {
		MUSIC = "Traitors.Music_IAF_Win",
		VOICE = "Traitors.Announcer_IAF_Win",
	},
	TRAITOR = {
		MUSIC = "Traitors.Music_Traitor_Win",
		VOICE = "Traitors.Announcer_Traitor_Win",
	},
};

MAP <- { // 地图

	// Area 9800 系列
	_9800_1 = 1,
	_9800_2 = 2,
	_9800_3 = 3,
	_9800_4 = 4,
	// Accident32
	ACC_1 = 5,
	ACC_2 = 6,
	ACC_3 = 7,
	ACC_4 = 8,
	ACC_5 = 9,
	ACC_6 = 10,

	// BioGen
	BIO_1 = 11,
	BIO_2 = 12,
	BIO_3 = 13,

	// Bonus
	BON_1 = 14,
	BON_2 = 15,
	BON_3 = 16,
	BON_4 = 17,
	BON_5 = 18,
	BON_6 = 19,
	BON_7 = 20,
	BON_8 = 21,
	BON_9 = 22,
	BON_10 = 23,
	BON_11 = 24,
	BON_12 = 25,

	// Jacobi
	JAC_1 = 26,
	JAC_2 = 27,
	JAC_3 = 28,
	JAC_4 = 29,
	JAC_5 = 30,
	JAC_6 = 31,
	JAC_7 = 32,

	// Lana
	LANA_1 = 33,
	LANA_2 = 34,
	LANA_3 = 35,
	LANA_4 = 36,
	LANA_5 = 37,

	// NH
	NH_1 = 38,
	NH_2 = 39,
	NH_3 = 40,

	// Operation Clean Sweep
	OCS_1 = 41,
	OCS_2 = 42,
	OCS_3 = 43,

	// Paranoia
	PARA_1 = 44,
	PARA_2 = 45,
	PARA_3 = 46,
	PARA_4 = 47,
	PARA_5 = 48,

	// Reduction
	RED_1 = 49,
	RED_2 = 50,
	RED_3 = 51,
	RED_4 = 52,
	RED_5 = 53,
	RED_6 = 54,

	// Research7
	RES_1 = 55,
	RES_2 = 56,
	RES_3 = 57,
	RES_4 = 58,

	// TFT
	TFT_1 = 59,
	TFT_2 = 60,
	TFT_3 = 61,

	// Tilarus-5
	TILA_1 = 62,
	TILA_2 = 63,
	TILA_3 = 64,
	TILA_4 = 65,
	TILA_5 = 66,
	TILA_6 = 67,
	TILA_7 = 68,
	TILA_8 = 69,
	TILA_9 = 70,

	OTHER = 999,
}

DAMAGE_TYPE <- {
	DMG_GENERIC = 0, // generic damage was done
	DMG_CRUSH = (1 << 0), // crushed by falling or moving object.
	// NOTE: It's assumed crush damage is occurring as a result of physics collision, so no extra physics force is generated by crush damage.
	// DON'T use DMG_CRUSH when damaging entities unless it's the result of a physics collision. You probably want DMG_CLUB instead.
	DMG_BULLET = (1 << 1), // shot
	DMG_SLASH = (1 << 2), // cut, clawed, stabbed
	DMG_BURN = (1 << 3), // heat burned
	DMG_VEHICLE = (1 << 4), // hit by a vehicle
	DMG_FALL = (1 << 5), // fell too far
	DMG_BLAST = (1 << 6), // explosive blast damage
	DMG_CLUB = (1 << 7), // crowbar, punch, headbutt
	DMG_SHOCK = (1 << 8), // electric shock
	DMG_SONIC = (1 << 9), // sound pulse shockwave
	DMG_ENERGYBEAM = (1 << 10), // laser or other high energy beam
	DMG_PREVENT_PHYSICS_FORCE = (1 << 11), // Prevent a physics force
	DMG_NEVERGIB = (1 << 12), // with this bit OR'd in, no damage type will be able to gib victims upon death
	DMG_ALWAYSGIB = (1 << 13), // with this bit OR'd in, any damage type can be made to gib victims upon death.
	DMG_DROWN = (1 << 14), // Drowning
	DMG_PARALYZE = (1 << 15), // slows affected creature down
	DMG_NERVEGAS = (1 << 16), // nerve toxins, very bad
	DMG_POISON = (1 << 17), // blood poisoning - heals over time like drowning damage
	DMG_RADIATION = (1 << 18), // radiation exposure
	DMG_DROWNRECOVER = (1 << 19), // drowning recovery
	DMG_ACID = (1 << 20), // toxic chemicals or acid burns
	DMG_SLOWBURN = (1 << 21), // in an oven
	DMG_REMOVENORAGDOLL = (1 << 22), // with this bit OR'd in, no ragdoll will be created, and the target will be quietly removed.
	// use this to kill an entity that you've already got a server-side ragdoll for
	DMG_PHYSGUN = (1 << 23), // Hit by manipulator. Usually doesn't do any damage.
	DMG_PLASMA = (1 << 24), // Shot by Cremator
	DMG_AIRBOAT = (1 << 25), // Hit by the airboat's gun
	DMG_DISSOLVE = (1 << 26), // Dissolving!
	DMG_BLAST_SURFACE = (1 << 27), // A blast on the surface of water that cannot harm things underwater
	DMG_DIRECT = (1 << 28),
	DMG_BUCKSHOT = (1 << 29) // not quite a bullet. Little, rounder, different.
}

AMMO_NAME <- [
	"asw_ammo_drop",
	"asw_ammo_rifle",
	"asw_ammo_autogun",
	"asw_ammo_shotgun",
	"asw_ammo_vindicator",
	"asw_ammo_flamer",
	"asw_ammo_pistol",
	"asw_ammo_mining_laser",
	"asw_ammo_railgun",
	"asw_ammo_chainsaw",
	"asw_ammo_pdw",
	"asw_weapon_ammo_satchel",
	"asw_pickup_ammo_satchel"
];

ENGINE_CONTENTS <- {
	CONTENTS_EMPTY = 0, // No contents
	CONTENTS_SOLID = 0x1, // an eye is never valid in a solid
	CONTENTS_WINDOW = 0x2, // translucent, but not watery (glass)
	CONTENTS_AUX = 0x4,
	CONTENTS_GRATE = 0x8, // alpha-tested "grate" textures.  Bullets/sight pass through, but solids don't
	CONTENTS_SLIME = 0x10,
	CONTENTS_WATER = 0x20,
	CONTENTS_BLOCKLOS = 0x40, // block AI line of sight
	CONTENTS_OPAQUE = 0x80, // things that cannot be seen through (may be non-solid though)
	CONTENTS_TESTFOGVOLUME = 0x100,
	CONTENTS_UNUSED = 0x200,
	CONTENTS_TEAM1 = 0x800, // per team contents used to differentiate collisions
	CONTENTS_TEAM2 = 0x1000, // between players and objects on different teams
	CONTENTS_IGNORE_NODRAW_OPAQUE = 0x2000, // ignore CONTENTS_OPAQUE on surfaces that have SURF_NODRAW
	CONTENTS_MOVEABLE = 0x4000, // hits entities which are MOVETYPE_PUSH (doors, plats, etc.)
	CONTENTS_AREAPORTAL = 0x8000, // remaining contents are non-visible, and don't eat brushes
	CONTENTS_PLAYERCLIP = 0x10000,
	CONTENTS_MONSTERCLIP = 0x20000,
	CONTENTS_CURRENT_0 = 0x40000, // currents can be added to any other contents, and may be mixed
	CONTENTS_CURRENT_90 = 0x80000, // currents can be added to any other contents, and may be mixed
	CONTENTS_CURRENT_180 = 0x100000, // currents can be added to any other contents, and may be mixed
	CONTENTS_CURRENT_270 = 0x200000, // currents can be added to any other contents, and may be mixed
	CONTENTS_CURRENT_UP = 0x400000, // currents can be added to any other contents, and may be mixed
	CONTENTS_CURRENT_DOWN = 0x800000, // currents can be added to any other contents, and may be mixed
	CONTENTS_ORIGIN = 0x1000000, // removed before bsping an entity
	CONTENTS_MONSTER = 0x2000000, // should never be on a brush, only in game
	CONTENTS_DEBRIS = 0x4000000,
	CONTENTS_DETAIL = 0x8000000, // brushes to be added after vis leafs
	CONTENTS_TRANSLUCENT = 0x10000000, // auto set if any surface has trans
	CONTENTS_LADDER = 0x20000000,
	CONTENTS_HITBOX = 0x40000000, // use accurate hitboxes on trace
};

VGUI_ACTION <- {
	SCANNER_OPEN = 0x01000000,
	SCANNER_SCAN = 0x01010000
	SCANNER_CLOSE = 0x01FF0000,

	SILENCER_OPEN = 0x02000000,
	SILENCER_SILENCE = 0x02010000,
	SILENCER_CLOSE = 0x02FF0000,

	BIOCHEMIST_OPEN = 0x03000000,
	BIOCHEMIST_HEAL = 0x03010000,
	BIOCHEMIST_KILL = 0x03020000,
	BIOCHEMIST_CLOSE = 0x03FF0000,

	SHIELD_OPEN = 0x04000000,
	SHIELD_GIVE_MECHA = 0x04010000,
	SHIELD_CLOSE = 0x04FF0000,

	INFECTOR_OPEN = 0x05000000,
	INFECTOR_ABET = 0x05010000,
	INFECTOR_CLOSE = 0x05FF0000,
};

KEY_CODE <- {
	BUTTON_CODE_INVALID = -1,
	BUTTON_CODE_NONE = 0,
	KEY_FIRST = 0,
	KEY_NONE = 0,
	KEY_0 = 1,
	KEY_1 = 2,
	KEY_2 = 3,
	KEY_3 = 4,
	KEY_4 = 5,
	KEY_5 = 6,
	KEY_6 = 7,
	KEY_7 = 8,
	KEY_8 = 9,
	KEY_9 = 10,
	KEY_A = 11,
	KEY_B = 12,
	KEY_C = 13,
	KEY_D = 14,
	KEY_E = 15,
	KEY_F = 16,
	KEY_G = 17,
	KEY_H = 18,
	KEY_I = 19,
	KEY_J = 20,
	KEY_K = 21,
	KEY_L = 22,
	KEY_M = 23,
	KEY_N = 24,
	KEY_O = 25,
	KEY_P = 26,
	KEY_Q = 27,
	KEY_R = 28,
	KEY_S = 29,
	KEY_T = 30,
	KEY_U = 31,
	KEY_V = 32,
	KEY_W = 33,
	KEY_X = 34,
	KEY_Y = 35,
	KEY_Z = 36,
	KEY_PAD_0 = 37,
	KEY_PAD_1 = 38,
	KEY_PAD_2 = 39,
	KEY_PAD_3 = 40,
	KEY_PAD_4 = 41,
	KEY_PAD_5 = 42,
	KEY_PAD_6 = 43,
	KEY_PAD_7 = 44,
	KEY_PAD_8 = 45,
	KEY_PAD_9 = 46,
	KEY_PAD_DIVIDE = 47,
	KEY_PAD_MULTIPLY = 48,
	KEY_PAD_MINUS = 49,
	KEY_PAD_PLUS = 50,
	KEY_PAD_ENTER = 51,
	KEY_PAD_DECIMAL = 52,
	KEY_LBRACKET = 53,
	KEY_RBRACKET = 54,
	KEY_SEMICOLON = 55,
	KEY_APOSTROPHE = 56,
	KEY_BACKQUOTE = 57,
	KEY_COMMA = 58,
	KEY_PERIOD = 59,
	KEY_SLASH = 60,
	KEY_BACKSLASH = 61,
	KEY_MINUS = 62,
	KEY_EQUAL = 63,
	KEY_ENTER = 64,
	KEY_SPACE = 65,
	KEY_BACKSPACE = 66,
	KEY_TAB = 67,
	KEY_CAPSLOCK = 68,
	KEY_NUMLOCK = 69,
	KEY_ESCAPE = 70,
	KEY_SCROLLLOCK = 71,
	KEY_INSERT = 72,
	KEY_DELETE = 73,
	KEY_HOME = 74,
	KEY_END = 75,
	KEY_PAGEUP = 76,
	KEY_PAGEDOWN = 77,
	KEY_BREAK = 78,
	KEY_LSHIFT = 79,
	KEY_RSHIFT = 80,
	KEY_LALT = 81,
	KEY_RALT = 82,
	KEY_LCONTROL = 83,
	KEY_RCONTROL = 84,
	KEY_LWIN = 85,
	KEY_RWIN = 86,
	KEY_APP = 87,
	KEY_UP = 88,
	KEY_LEFT = 89,
	KEY_DOWN = 90,
	KEY_RIGHT = 91,
	KEY_F1 = 92,
	KEY_F2 = 93,
	KEY_F3 = 94,
	KEY_F4 = 95,
	KEY_F5 = 96,
	KEY_F6 = 97,
	KEY_F7 = 98,
	KEY_F8 = 99,
	KEY_F9 = 100,
	KEY_F10 = 101,
	KEY_F11 = 102,
	KEY_F12 = 103,
	KEY_CAPSLOCKTOGGLE = 104,
	KEY_NUMLOCKTOGGLE = 105,
	KEY_SCROLLLOCKTOGGLE = 106,

	KEY_LAST = 106,
	KEY_COUNT = 107,

	// Mouse
	MOUSE_FIRST = 107,

	MOUSE_LEFT = 107,
	MOUSE_RIGHT = 108,
	MOUSE_MIDDLE = 109,
	MOUSE_4 = 110,
	MOUSE_5 = 111,
	MOUSE_WHEEL_UP = 112, // A fake button which is 'pressed' and 'released' when the wheel is moved up
	MOUSE_WHEEL_DOWN = 113, // A fake button which is 'pressed' and 'released' when the wheel is moved down

	MOUSE_LAST = 113,
	MOUSE_COUNT = 7,

	// Joystick
	JOYSTICK_FIRST = 114,

	JOYSTICK_FIRST_BUTTON = 114,
	JOYSTICK_LAST_BUTTON = 241,
	JOYSTICK_FIRST_POV_BUTTON = 242,
	JOYSTICK_LAST_POV_BUTTON = 257,
	JOYSTICK_FIRST_AXIS_BUTTON = 258,
	JOYSTICK_LAST_AXIS_BUTTON = 305,

	JOYSTICK_LAST = 305,

	BUTTON_CODE_LAST = 306,
	BUTTON_CODE_COUNT = 307,

	// Helpers for XBox 360
	KEY_XBUTTON_UP = 242, // POV buttons
	KEY_XBUTTON_RIGHT = 243,
	KEY_XBUTTON_DOWN = 244,
	KEY_XBUTTON_LEFT = 245,

	KEY_XBUTTON_A = 113, // Buttons
	KEY_XBUTTON_B = 114,
	KEY_XBUTTON_X = 116,
	KEY_XBUTTON_Y = 117,
	KEY_XBUTTON_LEFT_SHOULDER = 118,
	KEY_XBUTTON_RIGHT_SHOULDER = 119,
	KEY_XBUTTON_BACK = 120,
	KEY_XBUTTON_START = 121,
	KEY_XBUTTON_STICK1 = 122,
	KEY_XBUTTON_STICK2 = 123,
	KEY_XBUTTON_INACTIVE_START = 124,

	KEY_XSTICK1_RIGHT = 258, // XAXIS POSITIVE
	KEY_XSTICK1_LEFT = 259, // XAXIS NEGATIVE
	KEY_XSTICK1_DOWN = 260, // YAXIS POSITIVE
	KEY_XSTICK1_UP = 261, // YAXIS NEGATIVE
	KEY_XBUTTON_LTRIGGER = 262, // ZAXIS POSITIVE
	KEY_XBUTTON_RTRIGGER = 263, // ZAXIS NEGATIVE
	KEY_XSTICK2_RIGHT = 264, // UAXIS POSITIVE
	KEY_XSTICK2_LEFT = 265, // UAXIS NEGATIVE
	KEY_XSTICK2_DOWN = 266, // VAXIS POSITIVE
	KEY_XSTICK2_UP = 267, // VAXIS NEGATIVE

	// AS:RD - this keycode means a button has been "pressed" by a Steam Input config
	KEY_STEAM_INPUT = 145,
};